# Generated by Django 4.1.4 on 2022-12-29 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hellc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.IntegerField()),
                ('guest_number', models.SmallIntegerField()),
                ('guest1', models.IntegerField()),
                ('guest2', models.IntegerField()),
                ('guest3', models.IntegerField()),
                ('guest4', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
