# Generated by Django 4.1.4 on 2022-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellc', '0003_alter_room_guest1_alter_room_guest2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
