# Generated by Django 4.1.4 on 2022-12-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellc', '0004_alter_room_guest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='log',
            field=models.TextField(default='{}'),
        ),
    ]
