# Generated by Django 4.0.4 on 2023-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellc', '0006_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='status',
            field=models.CharField(default='start', max_length=100),
        ),
    ]
