# Generated by Django 4.0.4 on 2023-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellc', '0007_calendar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='is_arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worklog',
            name='is_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='is_chest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='is_shoulder',
            field=models.BooleanField(default=False),
        ),
    ]
