# Generated by Django 4.0.4 on 2022-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_actlog_notice_paper_paperadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(unique=True)),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('answer4', models.TextField()),
                ('answer5', models.TextField()),
                ('answer6', models.TextField()),
                ('answer7', models.TextField()),
                ('answer8', models.TextField()),
                ('answer9', models.TextField()),
                ('answer10', models.TextField()),
            ],
        ),
    ]
