# Generated by Django 4.0.4 on 2022-12-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_application_create_date_application_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='password',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='01012345678', max_length=11),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
