# Generated by Django 4.0.4 on 2022-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_customuser_myattribute_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('generation', models.SmallIntegerField()),
                ('is_opened', models.BooleanField(default=False)),
                ('question1', models.TextField(max_length=1000)),
                ('question2', models.TextField(max_length=1000)),
                ('question3', models.TextField(max_length=1000)),
                ('question4', models.TextField(max_length=1000)),
                ('question5', models.TextField(max_length=1000)),
                ('question6', models.TextField(max_length=1000)),
                ('question7', models.TextField(max_length=1000)),
                ('question8', models.TextField(max_length=1000)),
                ('question9', models.TextField(max_length=1000)),
                ('question10', models.TextField(max_length=1000)),
            ],
        ),
    ]
