# Generated by Django 4.0.4 on 2022-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opening',
            name='start_date',
            field=models.DateField(),
        ),
    ]
