# Generated by Django 4.0.4 on 2022-12-26 16:18

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_about_alter_opening_question1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'get_latest_by': builtins.id},
        ),
    ]
