# Generated by Django 4.0.4 on 2022-12-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'get_latest_by': 'id'},
        ),
    ]
