# Generated by Django 4.0.4 on 2022-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_type',
            field=models.CharField(choices=[('지원', '지원'), ('심사', '심사'), ('활동', '활동'), ('기타', '기타')], max_length=10),
        ),
    ]
